name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run format-check
      - run: npm run lint-check
      - run: npm run build
      - run: npm run pack
      - run: |
          if [ "$(git diff --name-only | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes to:"
            git diff --name-only
            exit 1
          fi
