name: Usage Count

on:
  workflow_dispatch

jobs:
  usage-count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          debug: true
        script: |
          const result = await github.search.repos({
            q: 'update-gradle-wrapper-action+in:file+language:yaml+path:.github/workflows'
          })
          console.log(result)
          console.log(result?.total_count)
